### ISSUE TITLE
Only one circle during Calibration step

### ISSUE THREAD

**Issue by mselleki** [hsogo/psychopy_tobii_controller#3]
Hi, 
I am facing a strange issue when trying to adapt your code to my PsychoPy Template : It recognizes my gaze well, but when I entered in calibration step, it only displays a circle at the middle of the screen, and not continuing for next one.

Do you have any insights on this problem ?

Thank you for this wonderful template you provide!
Ilyass , PhD student at Paris Brain Institute

**Comment by hsogo** [comment]
Hi,
Thank you for your interest in this package.
I'm sorry to say that I can't understand the phenomenon reported.  What version of PsychoPy do you use?  Do my sample codes (https://github.com/hsogo/psychopy_tobii_controller/tree/master/samples) work without problems on your PC setup?  I'd appreciate it if you send me a sample code for this problem.

**Comment by mselleki** [comment]
Hi, problem fixed ! it was a units problem. Thank you again, I managed to arrange your package along with my tasks
